import java.util.ArrayList;
import java.util.HashMap;

public class Main {
    public static void main(String[] args) {

        char[] charArray = { 'a', 'b', 'c', 'd', 'e', 'f' }; 
        int[] charfreq = { 5, 9, 12, 13, 16, 45 }; 
    
        HuffmanTree huff = new HuffmanTree(charArray, charfreq);

        //System.out.println(huff.root.toString());
        printCode(huff.root, "");

        HashMap<Character, String> hash = new HashMap<Character, String>();
        HashMap<Character, Byte> hash2 = new HashMap<Character, Byte>();
        HashCode(huff.root, "", hash2);

        System.out.println(hash.toString());

        //System.out.println("termino");
    }
    
    public static void printCode(HuffmanNode root, String s) 
    { 
  
        // base case; if the left and right are null 
        // then its a leaf node and we print 
        // the code s generated by traversing the tree. 
        if (root.left == null && root.right == null
            && Character.isLetter(root.c)) { 
  
            // c is the character in the node 
            System.out.println(root.c + ":" + s); 
  
            return; 
        } 
  
        // if we go to left then add "0" to the code. 
        // if we go to the right add"1" to the code. 
  
        // recursive calls for left and 
        // right sub-tree of the generated tree. 
        printCode(root.left, s + "0"); 
        printCode(root.right, s + "1"); 
    }

    public static void HashCode(HuffmanNode root, String s, HashMap<Character,Byte> hash) 
    { 
  
        // base case; if the left and right are null 
        // then its a leaf node and we print 
        // the code s generated by traversing the tree. 
        if (root.left == null && root.right == null
            && Character.isLetter(root.c)) { 
  
            // c is the character in the node 
            System.out.println(s);
            System.out.println(Byte.parseByte(s));
            hash.put(root.c,Byte.parseByte(s));
            System.out.println(hash.toString());
  
            return; 
        } 
  
        // if we go to left then add "0" to the code. 
        // if we go to the right add"1" to the code. 
  
        // recursive calls for left and 
        // right sub-tree of the generated tree. 
        HashCode(root.left, s + "0", hash); 
        HashCode(root.right, s + "1", hash); 
    }

}
